const signs = [
  { id: 'APR-09', text: 'Cars, Bikes, Vans and SUVs only' },
  { id: 'APR-10', text: 'Busses, Lorries, Cars and Bikes only' },
  { id: 'APR-11', text: 'Busses and Lorries only' },
  { id: 'APR-12', text: 'Three wheelers and Tractors only' },
  { id: 'APR-14', text: 'Pedestrians, two wheelers, Three wheelers and karts are not allowed' },
  { id: 'DWS-01', text: 'The road is slightly curving ahead to left' },
  { id: 'DWS-02', text: 'The road is slightly curving ahead to right' },
  { id: 'DWS-03', text: 'Z bend ahead to the left' },
  { id: 'DWS-04', text: 'Z bend ahead to the right' },
  { id: 'DWS-09', text: 'The road is narrowed from both sides, please slow down' },
  { id: 'DWS-10', text: 'The road is narrowed in the left, please slow down' },
  { id: 'DWS-11', text: 'The road is narrowed in the right, please slow down' },
  { id: 'DWS-12', text: 'Four way junction is ahead, drive attentively' },
  { id: 'DWS-13', text: '' },
  { id: 'DWS-14', text: '' },
  { id: 'DWS-15', text: 'T junction is ahead, drive attentively' },
  { id: 'DWS-16', text: 'Y junction is ahead, drive attentively' },
  { id: 'DWS-17', text: '' },
  { id: 'DWS-18', text: '' },
  { id: 'DWS-19', text: '' },
  { id: 'DWS-20', text: '' },
  { id: 'DWS-21', text: 'Narrow bridge ahead please do not overtake' },
  { id: 'DWS-25', text: 'Roundabout ahead please drive attentively' },
  { id: 'DWS-26', text: 'Color lights ahead' },
  { id: 'DWS-27', text: 'Steep descent ahead please drive slow' },
  { id: 'DWS-28', text: 'Steep ascent ahead drive carefully' },
  { id: 'DWS-29', text: 'The road is slippery, drive slow and pay attention!' },
  { id: 'DWS-32', text: 'Pedestrian crossing ahead, drive slow and pay attention to the road' },
  { id: 'DWS-33', text: 'School is ahead please slow down and pay attention to the road' },
  { id: 'DWS-35', text: 'Construstions ahead, please drive slow' },
  { id: 'DWS-36', text: 'Railyway tracks ahead, cross carefully' },
  { id: 'DWS-40', text: 'Pay attention to cyclist' },
  { id: 'DWS-41', text: 'Pay attention animals can intefere the road' },
  { id: 'DWS-42', text: 'Drive carefully and slow, Dam ahead' },
  { id: 'DWS-44', text: 'Speed bumps ahead, slow down' },
  { id: 'DWS-46', text: 'Speed traps ahead, slow down' },
  { id: 'MNS-01', text: 'Turn left' },
  { id: 'MNS-02', text: 'Turn right' },
  { id: 'MNS-03', text: 'Keep straight, no turning' },
  { id: 'MNS-04', text: 'Immediate bend to left drive carefully' },
  { id: 'MNS-05', text: 'Immediate bend to right drive carefully' },
  { id: 'MNS-06', text: 'Pass on to left, pay attention' },
  { id: 'MNS-07', text: 'Pass on to right, pay attention' },
  { id: 'MNS-09', text: 'Roundabout ahead please drive attentively' },
  { id: 'OSD-01', text: 'Pedestrian crossing ahead, drive slow and pay attention to the road' },
  { id: 'OSD-02', text: 'One-way street' },
  { id: 'OSD-03', text: 'Hospital ahead, please drive slow do not honk' },
  { id: 'OSD-04', text: 'Parking' },
  { id: 'OSD-06', text: 'Bus stand' },
  { id: 'OSD-07', text: 'Bus lane' },
  { id: 'OSD-16', text: '' },
  { id: 'OSD-17', text: '' },
  { id: 'OSD-26', text: 'Exit ahead' },
  { id: 'PHS-01', text: 'No entry' },
  { id: 'PHS-02', text: 'No turning to the left' },
  { id: 'PHS-03', text: 'No turning to the right' },
  { id: 'PHS-04', text: 'U turn is not allowed' },
  { id: 'PHS-05', text: 'Do not honk' },
  { id: 'PHS-23', text: 'No parking' },
  { id: 'PHS-24', text: 'No parking and standing' },
  { id: 'PRS-01', text: 'Stop' },
  { id: 'PRS-02', text: 'Give way' },
  { id: 'RSS-02', text: 'Maximum heigh allowed is 4.4 meters' },
  { id: 'SLS-100', text: 'Speed limit 100 km/h' },
  { id: 'SLS-15', text: 'Speed limit 15 km/h' },
  { id: 'SLS-40', text: 'Speed limit 40 km/h' },
  { id: 'SLS-50', text: 'Speed limit 50 km/h' },
  { id: 'SLS-60', text: 'Speed limit 60 km/h' },
  { id: 'SLS-70', text: 'Speed limit 70 km/h' },
  { id: 'SLS-80', text: 'Speed limit 80 km/h' },
  { id: 'TLS-C', text: 'Prepare to stop' },
  { id: 'TLS-E', text: 'Color lights not on operation' },
  { id: 'TLS-G', text: 'Green light, Go' },
  { id: 'TLS-R', text: 'Red light, stop' },
  { id: 'TLS-Y', text: 'Yellow light, Ready' },
];

  
  export default signs;
  